### ISSUE TITLE
工学云更新了

### ISSUE THREAD

**Issue by MoLeft** [laradocs/moguding-sdk-php#24]
现在打卡会提示“请到应用宝或者蘑菇丁/工学云网站下载最新版本APP”

**Comment by MoLeft** [comment]
工学云现在不允许“https://api.moguding.net:9000/session/user/v1/login”这个接口登录了，只能通过v3的去登录

**Comment by laradocs** [comment]
这里已经更新了：https://github.com/laradocs/moguding-solution
